// hindiLetters.ts
// Common data for Hindi letters (अ to अः) with word, image, and (optionally) sound.

export const hindiVowels = [
  { letter: 'अ', word: 'अनार', image: require('../../assets/images/अ.png'), sound: require('../../assets/sounds/01_अ.mp3') },
  { letter: 'आ', word: 'आम', image: require('../../assets/images/आ.png'), sound: require('../../assets/sounds/02_आ.mp3') },
  { letter: 'इ', word: 'इमली', image: require('../../assets/images/इ.png'), sound: require('../../assets/sounds/03_इ.mp3') },
  { letter: 'ई', word: 'ईख', image: require('../../assets/images/ई.png'), sound: require('../../assets/sounds/04_ई.mp3') },
  { letter: 'उ', word: 'उल्लू', image: require('../../assets/images/उ.png'), sound: require('../../assets/sounds/05_उ.mp3') },
  { letter: 'ऊ', word: 'ऊन', image: require('../../assets/images/ऊ.png'), sound: require('../../assets/sounds/06_ऊ.mp3') },
  { letter: 'ए', word: 'एड़ी', image: require('../../assets/images/ए.png'), sound: require('../../assets/sounds/07_ए.mp3') },
  { letter: 'ऐ', word: 'ऐनक', image: require('../../assets/images/ऐ.png'), sound: require('../../assets/sounds/08_ऐ.mp3') },
  { letter: 'ओ', word: 'ओखली', image: require('../../assets/images/ओ.png'), sound: require('../../assets/sounds/09_ओ.mp3') },
  { letter: 'औ', word: 'औरत', image: require('../../assets/images/औ.png'), sound: require('../../assets/sounds/10_औ.mp3') },
  { letter: 'अं', word: 'अंगूर', image: require('../../assets/images/अं.png'), sound: require('../../assets/sounds/11_अं.mp3') },
  { letter: 'अः', word: 'अः', image: require('../../assets/images/अः.png'), sound: require('../../assets/sounds/12_अः.mp3') },
];

export const hindiMatras = [
  { letter: 'ा', word: 'आ की मात्रा', example: 'का', sound: require('../../assets/sounds/02_आ.mp3') },
  { letter: 'ि', word: 'इ की मात्रा', example: 'कि', sound: require('../../assets/sounds/03_इ.mp3') },
  { letter: 'ी', word: 'ई की मात्रा', example: 'की', sound: require('../../assets/sounds/04_ई.mp3') },
  { letter: 'ु', word: 'उ की मात्रा', example: 'कु', sound: require('../../assets/sounds/05_उ.mp3') },
  { letter: 'ू', word: 'ऊ की मात्रा', example: 'कू', sound: require('../../assets/sounds/06_ऊ.mp3') },
  { letter: 'ृ', word: 'ऋ की मात्रा', example: 'कृ', sound: require('../../assets/sounds/01_अ.mp3') },
  { letter: 'े', word: 'ए की मात्रा', example: 'के', sound: require('../../assets/sounds/07_ए.mp3') },
  { letter: 'ै', word: 'ऐ की मात्रा', example: 'कै', sound: require('../../assets/sounds/08_ऐ.mp3') },
  { letter: 'ो', word: 'ओ की मात्रा', example: 'को', sound: require('../../assets/sounds/09_ओ.mp3') },
  { letter: 'ौ', word: 'औ की मात्रा', example: 'कौ', sound: require('../../assets/sounds/10_औ.mp3') },
  { letter: 'ं', word: 'अं की मात्रा', example: 'कं', sound: require('../../assets/sounds/11_अं.mp3') },
  { letter: 'ः', word: 'अः की मात्रा', example: 'कः', sound: require('../../assets/sounds/12_अः.mp3') },
];

export const hindiVowelsWithMatras = [
  ...hindiVowels,
  ...hindiMatras,
];

export const hindiConsonants = [
  { letter: 'क', word: 'कबूतर', image: require('../../assets/images/kabootar.png'), sound: require('../../assets/sounds/13_क.mp3') },
  { letter: 'ख', word: 'खरगोश', image: require('../../assets/images/khargosh.png'), sound: require('../../assets/sounds/14_ख.mp3') },
  { letter: 'ग', word: 'गमला', image: require('../../assets/images/gamla.png'), sound: require('../../assets/sounds/15_ग.mp3') },
  { letter: 'घ', word: 'घड़ी', image: require('../../assets/images/ghadi.png'), sound: require('../../assets/sounds/16_घ.mp3') },
  { letter: 'ङ', word: 'ङग', image: require('../../assets/images/ng.png'), sound: require('../../assets/sounds/17_ङ.mp3') },
  { letter: 'च', word: 'चमच', image: require('../../assets/images/chamach.png'), sound: require('../../assets/sounds/18_च.mp3') },
  { letter: 'छ', word: 'छाता', image: require('../../assets/images/chhata.png'), sound: require('../../assets/sounds/19_छ.mp3') },
  { letter: 'ज', word: 'जग', image: require('../../assets/images/jag.png'), sound: require('../../assets/sounds/20_ज.mp3') },
  { letter: 'झ', word: 'झंडा', image: require('../../assets/images/jhanda.png'), sound: require('../../assets/sounds/21_झ.mp3') },
  { letter: 'ञ', word: 'ञ', image: require('../../assets/images/nya.png'), sound: require('../../assets/sounds/22_ञ.mp3') },
  { letter: 'ट', word: 'टमाटर', image: require('../../assets/images/tamatar.png'), sound: require('../../assets/sounds/23_ट.mp3') },
  { letter: 'ठ', word: 'ठठेरा', image: require('../../assets/images/thathera.png'), sound: require('../../assets/sounds/24_ठ.mp3') },
  { letter: 'ड', word: 'डमरू', image: require('../../assets/images/damaru.png'), sound: require('../../assets/sounds/25_ड.mp3') },
  { letter: 'ढ', word: 'ढोल', image: require('../../assets/images/dhol.png'), sound: require('../../assets/sounds/26_ढ.mp3') },
  { letter: 'ण', word: 'ण', image: require('../../assets/images/n.png'), sound: require('../../assets/sounds/27_ण.mp3') },
  { letter: 'त', word: 'तरबूज', image: require('../../assets/images/tarbuj.png'), sound: require('../../assets/sounds/28_त.mp3') },
  { letter: 'थ', word: 'थरमस', image: require('../../assets/images/tharmas.png'), sound: require('../../assets/sounds/29_थ.mp3') },
  { letter: 'द', word: 'दवात', image: require('../../assets/images/dawat.png'), sound: require('../../assets/sounds/30_द.mp3') },
  { letter: 'ध', word: 'धनुष', image: require('../../assets/images/dhanush.png'), sound: require('../../assets/sounds/31_ध.mp3') },
  { letter: 'न', word: 'नल', image: require('../../assets/images/nal.png'), sound: require('../../assets/sounds/32_न.mp3') },
  { letter: 'प', word: 'पतंग', image: require('../../assets/images/patang.png'), sound: require('../../assets/sounds/33_प.mp3') },
  { letter: 'फ', word: 'फल', image: require('../../assets/images/phil.png'), sound: require('../../assets/sounds/34_फ.mp3') },
  { letter: 'ब', word: 'बतख', image: require('../../assets/images/batakh.png'), sound: require('../../assets/sounds/35_ब.mp3') },
  { letter: 'भ', word: 'भालू', image: require('../../assets/images/bhalu.png'), sound: require('../../assets/sounds/36_भ.mp3') },
  { letter: 'म', word: 'मछली', image: require('../../assets/images/machhli.png'), sound: require('../../assets/sounds/37_म.mp3') },
  { letter: 'य', word: 'यज्ञ', image: require('../../assets/images/yagya.png'), sound: require('../../assets/sounds/38_य.mp3') },
  { letter: 'र', word: 'रथ', image: require('../../assets/images/rath.png'), sound: require('../../assets/sounds/39_र.mp3') },
  { letter: 'ल', word: 'लट्टू', image: require('../../assets/images/lattu.png'), sound: require('../../assets/sounds/40_ल.mp3') },
  { letter: 'व', word: 'वायु', image: require('../../assets/images/vayu.png'), sound: require('../../assets/sounds/41_व.mp3') },
  { letter: 'श', word: 'शेर', image: require('../../assets/images/sheer.png'), sound: require('../../assets/sounds/42_श.mp3') },
  { letter: 'ष', word: 'षट्कोण', image: require('../../assets/images/satkona.png'), sound: require('../../assets/sounds/43_ष.mp3') },
  { letter: 'स', word: 'सपेरा', image: require('../../assets/images/sapera.png'), sound: require('../../assets/sounds/44_स.mp3') },
  { letter: 'ह', word: 'हाथी', image: require('../../assets/images/hati.png'), sound: require('../../assets/sounds/45_ह.mp3') },
  { letter: 'क्ष', word: 'क्षत्रिय', image: require('../../assets/images/krshtriya.png'), sound: require('../../assets/sounds/46_क्ष.mp3') },
  { letter: 'त्र', word: 'त्रिशूल', image: require('../../assets/images/trishool.png'), sound: require('../../assets/sounds/47_त्र.mp3') },
  { letter: 'ज्ञ', word: 'ज्ञानी', image: require('../../assets/images/jyagya.png'), sound: require('../../assets/sounds/48_ज्ञ.mp3') },
];

// Barakhadi - Consonant + Vowel combinations
export const barakhadi = [
  {
    consonant: 'क',
    combinations: [
      { syllable: 'क', matra: '्', vowel: 'अ' },
      { syllable: 'का', matra: 'ा', vowel: 'आ' },
      { syllable: 'कि', matra: 'ि', vowel: 'इ' },
      { syllable: 'की', matra: 'ी', vowel: 'ई' },
      { syllable: 'कु', matra: 'ु', vowel: 'उ' },
      { syllable: 'कू', matra: 'ू', vowel: 'ऊ' },
      { syllable: 'कृ', matra: 'ृ', vowel: 'ऋ' },
      { syllable: 'के', matra: 'े', vowel: 'ए' },
      { syllable: 'कै', matra: 'ै', vowel: 'ऐ' },
      { syllable: 'को', matra: 'ो', vowel: 'ओ' },
      { syllable: 'कौ', matra: 'ौ', vowel: 'औ' },
      { syllable: 'कं', matra: 'ं', vowel: 'अं' },
      { syllable: 'कः', matra: 'ः', vowel: 'अः' },
    ]
  },
  {
    consonant: 'ख',
    combinations: [
      { syllable: 'ख', matra: '्', vowel: 'अ' },
      { syllable: 'खा', matra: 'ा', vowel: 'आ' },
      { syllable: 'खि', matra: 'ि', vowel: 'इ' },
      { syllable: 'खी', matra: 'ी', vowel: 'ई' },
      { syllable: 'खु', matra: 'ु', vowel: 'उ' },
      { syllable: 'खू', matra: 'ू', vowel: 'ऊ' },
      { syllable: 'खृ', matra: 'ृ', vowel: 'ऋ' },
      { syllable: 'खे', matra: 'े', vowel: 'ए' },
      { syllable: 'खै', matra: 'ै', vowel: 'ऐ' },
      { syllable: 'खो', matra: 'ो', vowel: 'ओ' },
      { syllable: 'खौ', matra: 'ौ', vowel: 'औ' },
      { syllable: 'खं', matra: 'ं', vowel: 'अं' },
      { syllable: 'खः', matra: 'ः', vowel: 'अः' },
    ]
  },
  {
    consonant: 'ग',
    combinations: [
      { syllable: 'ग', matra: '्', vowel: 'अ' },
      { syllable: 'गा', matra: 'ा', vowel: 'आ' },
      { syllable: 'गि', matra: 'ि', vowel: 'इ' },
      { syllable: 'गी', matra: 'ी', vowel: 'ई' },
      { syllable: 'गु', matra: 'ु', vowel: 'उ' },
      { syllable: 'गू', matra: 'ू', vowel: 'ऊ' },
      { syllable: 'गृ', matra: 'ृ', vowel: 'ऋ' },
      { syllable: 'गे', matra: 'े', vowel: 'ए' },
      { syllable: 'गै', matra: 'ै', vowel: 'ऐ' },
      { syllable: 'गो', matra: 'ो', vowel: 'ओ' },
      { syllable: 'गौ', matra: 'ौ', vowel: 'औ' },
      { syllable: 'गं', matra: 'ं', vowel: 'अं' },
      { syllable: 'गः', matra: 'ः', vowel: 'अः' },
    ]
  },
  {
    consonant: 'घ',
    combinations: [
      { syllable: 'घ', matra: '्', vowel: 'अ' },
      { syllable: 'घा', matra: 'ा', vowel: 'आ' },
      { syllable: 'घि', matra: 'ि', vowel: 'इ' },
      { syllable: 'घी', matra: 'ी', vowel: 'ई' },
      { syllable: 'घु', matra: 'ु', vowel: 'उ' },
      { syllable: 'घू', matra: 'ू', vowel: 'ऊ' },
      { syllable: 'घृ', matra: 'ृ', vowel: 'ऋ' },
      { syllable: 'घे', matra: 'े', vowel: 'ए' },
      { syllable: 'घै', matra: 'ै', vowel: 'ऐ' },
      { syllable: 'घो', matra: 'ो', vowel: 'ओ' },
      { syllable: 'घौ', matra: 'ौ', vowel: 'औ' },
      { syllable: 'घं', matra: 'ं', vowel: 'अं' },
      { syllable: 'घः', matra: 'ः', vowel: 'अः' },
    ]
  },
  {
    consonant: 'ङ',
    combinations: [
      { syllable: 'ङ', matra: '्', vowel: 'अ' },
      { syllable: 'ङा', matra: 'ा', vowel: 'आ' },
      { syllable: 'ङि', matra: 'ि', vowel: 'इ' },
      { syllable: 'ङी', matra: 'ी', vowel: 'ई' },
      { syllable: 'ङु', matra: 'ु', vowel: 'उ' },
      { syllable: 'ङू', matra: 'ू', vowel: 'ऊ' },
      { syllable: 'ङृ', matra: 'ृ', vowel: 'ऋ' },
      { syllable: 'ङे', matra: 'े', vowel: 'ए' },
      { syllable: 'ङै', matra: 'ै', vowel: 'ऐ' },
      { syllable: 'ङो', matra: 'ो', vowel: 'ओ' },
      { syllable: 'ङौ', matra: 'ौ', vowel: 'औ' },
      { syllable: 'ङं', matra: 'ं', vowel: 'अं' },
      { syllable: 'ङः', matra: 'ः', vowel: 'अः' },
    ]
  },
];
