import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const TILE_SIZE = width * 0.36;

export const weekDaysQuizStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff8e1',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  rewardRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    marginBottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 30,
  },
  reward: {
    fontSize: 32,
    marginHorizontal: 2,
  },
  quizBlock: {
    alignItems: 'center',
    width: '100%',
    flex: 1,
    justifyContent: 'center',
  },
  resultBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    width: '100%',
  },
  heading: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ff9800',
    marginBottom: 24,
    textAlign: 'center',
  },
  question: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1976d2',
    marginBottom: 16,
    marginTop: 10,
    textAlign: 'center',
  },
  optionsGrid2x2: {
    marginVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  optionTile2x2: {
    width: TILE_SIZE,
    height: TILE_SIZE,
    backgroundColor: '#fff',
    borderRadius: 18,
    marginHorizontal: 8,
    marginVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    paddingVertical: 0,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  hindi: {
    fontSize: 32,
    color: '#1976d2',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 2,
  },
  english: {
    fontSize: 18,
    color: '#6d4c41',
    letterSpacing: 1,
    textAlign: 'center',
  },
  audioBtn: {
    marginTop: 4,
    padding: 4,
  },
  audioIcon: {
    fontSize: 22,
    color: '#1976d2',
  },
  nav: {
    flexDirection: 'row',
    gap: 20,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBtn: {
    paddingVertical: 14,
    paddingHorizontal: 22,
    borderRadius: 30,
    backgroundColor: '#1976d2',
    elevation: 2,
    minWidth: 120,
    alignItems: 'center',
    marginHorizontal: 8,
  },
  navBtnText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  score: {
    fontSize: 28,
    marginTop: 8,
    color: '#333',
    fontWeight: '500',
    textAlign: 'center',
  },
});